### ISSUE TITLE
 Bot has failed to access the log group/channel.   Reason : UserIsBot.

### ISSUE THREAD

**Issue by lord-dubious** [venombolteop/VenomMusic#12]
when i launcj i get this issue i , the logger id is the id for the music bot i put in the private group is that correct?

**Comment by venombolteop** [comment]
Yes correct but need old group for logger id to working. 
Maybe your log group will be 6 months or more older.

**Comment by venombolteop** [comment]
> when i launcj i get this issue i , the logger id is the id for the music bot i put in the private group is that correct?

Wait will you put bot id in logger id ? It's wrong ❌

**Comment by lord-dubious** [comment]
oh wow
so do i move evrything to an old group??

**Comment by venombolteop** [comment]
> oh wow so do i move evrything to an old group??

You use bot id instead of log group id

**Comment by lord-dubious** [comment]
Reason : UserIsBot. when i use bot id

**Comment by venombolteop** [comment]
> Reason : UserIsBot. when i use bot id

Use group id not bot id
